### ISSUE TITLE
Proposed renaming and sectioning

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/json-ld-bp#15]
I'd like to rename the BP to "JSON-LD Best Practices" (removing the 1.1), and break the sections up into:
 - Authoring
   - contexts
   - data documents
 - Publishing
 - Consuming

**Comment by ajs6f** [comment]
What is the distinction between Authoring and Publishing? Is it in whether the context is being written or re-used?

**Comment by BigBlueHat** [comment]
Authoring would be about what goes into the JSON-LD document itself--i.e. `@context` ordering, when to use language/id maps, etc.

Publishing would be about putting that document someplace(s) for distribution--i.e. embedding in HTML, serving over HTTP, embedding in email, etc.

**Comment by ajs6f** [comment]
Okay. Would you be interested in breaking down `Authoring` to authoring contexts and authoring instance data?

**Comment by BigBlueHat** [comment]
Definitely. Good call.

**Comment by BigBlueHat** [comment]
I've updated the issue accordingly.
