### ISSUE TITLE
Streaming Profiles for JSON-LD to/from RDF

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-bp#4]
There have been some discussions on what it would take to be able to do a streaming parse of JSON-LD into Quads, and similarly to generate compliant JSON-LD from a stream of quads. Describing these as some kind of a profile would be useful for implementations that expect to work in a streaming environment, when it's not feasible to work on an entire document basis.

As currently stated, the JSON-LD to RDF algorithm requires expanding the document and creating a node map. A profile of JSON-LD which used a flattened array of node objects, where each node object could be independently expanded and no flattening is required could facilitate deserializing an arbitrarily long JSON-LD source to Quads. (Some simplifying restrictions on shared lists may be necessary). Outer document is an object, containing `@context` and `@graph` only; obviously, this only will work for systems that can access key/values in order, and for systems that ensure that `@context` comes lexically before `@graph` in the output. Obviously, only implementations that can read and write JSON objects with key ordering intact will be able to take advantage of such streaming capability.

Fo serializing RDF to JSON-LD, expectations on the grouping of quads with the same graph name and subject are necessary to reduce serialization cost, and marshaling components of RDF Lists is likely not feasible. Even if graph name/subject grouping is not maintained in the input, the resulting output will still represent a valid JSON-LD document, although it may require flattening for further processing. (Many triple stores will, in fact, generate statements/quads properly grouped, so this is likely not an issue in real world applications).

Original issue [Streaming Profiles for JSON-LD to/from RDF #434](https://github.com/json-ld/json-ld.org/issues/434).

**Comment by ajs6f** [comment]
Hm. Just thinking out loud, but I wonder if this would be even better placed as a Note separate from the BP document. Maybe, maybe not. In favor, I think it's a bit (or maybe a lot, depending on your POV) more advanced than other topics we expect to cover in the BP doc. Against, why multiply documents? We have several already…

**Comment by rubensworks** [comment]
@BigBlueHat I just went through this issue and #5, and I can confirm that all information in here is summarized in #5, so we can safely close this one here.
